#!/bin/sh
#
# @name Shuriken backup frame with shuriken1 and base2 parameters
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Vladimir Savelyev <vms@flyfire.io>
#

. ${R}etc/init.d/rc.mc_defaults
. ${R}etc/init.d/airframes/ff_base
. ${R}etc/init.d/airframes/ff_shuriken1

param set-default GPS_1_PROTOCOL 6 # NMEA
param set-default SER_GPS1_BAUD 460800
