#!/bin/sh
#
# @name Shuriken with base1 parameters
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Vladimir Savelyev <vms@flyfire.io>
#

. ${R}etc/init.d/airframes/ff_base1
. ${R}etc/init.d/airframes/ff_shuriken
