#!/bin/sh
#
# @name Shuriken master frame
# @type Quadrotor x
# @class Copter
#
# @maintainer Vladimir Savelyev <vms@flyfire.io>
#

. ${R}etc/init.d/airframes/ff_base2
. ${R}etc/init.d/airframes/ff_shuriken2

param set GPS_1_PROTOCOL 6 # NMEA
param set SER_GPS1_BAUD 460800
