#!/bin/sh
#
# @name Shuriken
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Vladimir Savelyev <vms@flyfire.io>
#

. ${R}etc/init.d/airframes/4998_kaiken

# Override 4998_kaiken parameters
param set-default CAL_MAG_COMP_TYP 1

param set-default CAL_MAG0_XCOMP -0.226
param set-default CAL_MAG0_YCOMP 0.253
param set-default CAL_MAG0_ZCOMP -0.031

param set-default IMU_DGYRO_CUTOFF 30
param set-default IMU_GYRO_CUTOFF 70
param set-default MC_ROLLRATE_D 0.001
param set-default MC_PITCHRATE_D 0.001

param set-default MPC_LAND_SPEED 0.1
param set-default MPC_LAND_ALT2 1
param set-default EKF2_BARO_CTRL 0
