#!/bin/sh
#
# @name Kaiken with dual-band gnss receiver
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Vladimir Savelyev <vms@flyfire.io>
#

. ${R}etc/init.d/airframes/4999_kaiken

# Override 4999_kaiken parameters
param set-default GPS_1_PROTOCOL 6
param set-default SER_GPS1_BAUD 460800
