#!/bin/sh
#
# @name Kaiken with u-blox gnss receiver
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Nikita Rodichenko <nsr@flyfire.io>
#

. ${R}etc/init.d/rc.mc_defaults
. ${R}etc/init.d/airframes/ff_base
. ${R}etc/init.d/airframes/ff_kaiken

# u-blox
param set-default GPS_1_PROTOCOL 1
param set-default GPS_UBX_DYNMODEL 7
