#!/bin/sh
#
# @name Kaiken
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Nikita Rodichenko <nsr@flyfire.io>
#

. ${R}etc/init.d/rc.mc_defaults

param set-default IMU_DGYRO_CUTOFF 50
param set-default IMU_GYRO_CUTOFF 90

# DShot
param set-default PWM_MAIN_TIM0 -5
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default DSHOT_MIN 0.075

# Rotors
param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.15
param set-default CA_ROTOR0_PY 0.15
param set-default CA_ROTOR1_PX -0.15
param set-default CA_ROTOR1_PY -0.15
param set-default CA_ROTOR2_PX 0.15
param set-default CA_ROTOR2_PY -0.15
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.15
param set-default CA_ROTOR3_PY 0.15
param set-default CA_ROTOR3_KM -0.05

# Smart battery
param set-default BAT1_N_CELLS 2
param set-default BAT1_SOURCE 1
param set-default BAT_CRIT_THR 0.07

# Sensors & Calibration
param set-default CAL_MAG0_ROT 12
param set-default CAL_MAG0_ID 527625
param set-default CAL_MAG0_PRIO 100
param set-default CAL_MAG1_ID 0
param set-default CAL_MAG1_PRIO 0
param set-default SENS_MAG_AUTOROT 0
param set-default CAL_MAG_SIDES 63
param set-default SENS_MAG_SIDES 63
param set-default SENS_BOARD_ROT 6
param set-default SENS_BOARD_X_OFF 0.001
param set-default SENS_BOARD_Y_OFF 0.001
param set-default EKF2_ABL_LIM 0.4
param set-default EKF2_GPS_POS_Z 0.0
param set-default EKF2_GPS_P_GATE 5
param set-default EKF2_GPS_P_NOISE 0.3
param set-default EKF2_GPS_V_NOISE 0.3
param set-default EKF2_HGT_REF 1
param set-default EKF2_REQ_HDRIFT 0.05
param set-default EKF2_REQ_VDRIFT 0.05
param set-default GPS_UBX_DYNMODEL 7
param set-default GPS_1_CONFIG 201

# RC
param set-default COM_FLTMODE1 8
param set-default COM_FLTMODE2 8
param set-default COM_FLTMODE3 1
param set-default COM_FLTMODE4 1
param set-default COM_FLTMODE5 2
param set-default COM_FLTMODE6 2
param set-default RC1_MAX 2005
param set-default RC1_MIN 982
param set-default RC1_TRIM 1495
param set-default RC2_MAX 2005
param set-default RC2_MIN 982
param set-default RC2_TRIM 1495
param set-default RC3_MAX 2005
param set-default RC3_MIN 982
param set-default RC3_TRIM 982
param set-default RC4_MAX 2005
param set-default RC4_MIN 982
param set-default RC4_TRIM 1495
param set-default RC5_MAX 2005
param set-default RC5_MIN 982
param set-default RC5_TRIM 1495
param set-default RC6_MAX 2005
param set-default RC6_MIN 982
param set-default RC6_TRIM 1495
param set-default RC7_MAX 2005
param set-default RC7_MIN 982
param set-default RC7_TRIM 1495
param set-default RC_CHAN_CNT 18
param set-default RC_MAP_FLTMODE 5
param set-default RC_MAP_PITCH 1
param set-default RC_MAP_POSCTL_SW 0
param set-default RC_MAP_RATT_SW 0
param set-default RC_MAP_RETURN_SW 0
param set-default RC_MAP_ROLL 2
param set-default RC_MAP_STAB_SW 0
param set-default RC_MAP_THROTTLE 3
param set-default RC_MAP_YAW 4

# Failsafes
param set-default COM_LOW_BAT_ACT 0
param set-default GF_ACTION 5 # Land mode
param set-default GF2_ACTION 4 # Terminate
param set-default GF_ALTMODE 0
param set-default GF_COUNT -1
param set-default GF_SOURCE 1
param set-default COM_FAIL_ACT_T 0
param set-default RTL_CONE_ANG 0
param set-default RTL_DESCEND_ALT 6
param set-default RTL_LAND_DELAY 5.0
param set-default RTL_MIN_DIST 0.0
param set-default RTL_RETURN_ALT 10
param set-default RTL_TYPE 0
param set-default RTL_TIME_MARGIN -1
param set-default RTL_TIME_FACTOR 0
param set-default COM_OBL_RC_ACT 4
param set-default COM_POSCTL_NAVL 1 # Land/Descend

# PID Tuning
param set-default MC_PITCHRATE_D 0.002
param set-default MC_PITCHRATE_I 0.2
param set-default MC_PITCHRATE_K 1
param set-default MC_PITCHRATE_MAX 220
param set-default MC_PITCHRATE_P 0.1
param set-default MC_PITCH_P 6.5
param set-default MC_ROLLRATE_D 0.002
param set-default MC_ROLLRATE_K 1
param set-default MC_ROLLRATE_MAX 220
param set-default MC_ROLLRATE_P 0.1
param set-default MC_ROLL_P 6.5
param set-default MC_YAWRATE_MAX 60
param set-default MC_YAWRATE_P 0.2
param set-default MC_YAW_P 2.5
param set-default THR_MDL_FAC 0.3

# Navigation Tuning & Speeds
param set-default MPC_MANTHR_MIN 0.08
param set-default MPC_MAN_TILT_MAX 35
param set-default MPC_POS_MODE 0
param set-default MPC_THR_HOVER 0.50
param set-default MPC_TILTMAX_AIR 45
param set-default MPC_XY_CRUISE 5
param set-default MPC_XY_P 0.95
param set-default MPC_XY_VEL_MAX 10
param set-default MPC_YAWRAUTO_MAX 45
param set-default MPC_Z_VEL_MAX_UP 3
param set-default MPC_OB_SP_DELAY 350
param set-default NAV_ACC_RAD 1.2
param set-default NAV_RCL_ACT 0
param set-default LNDMC_ROT_MAX 80
param set-default LNDMC_TRIG_TIME 1

# Landing
param set-default MPC_Z_VEL_MAX_DN 3
param set-default MPC_LAND_SPEED 0.3
param set-default MPC_LAND_ALT1 10
param set-default MPC_LAND_ALT2 1

# Logging
param set-default SDLOG_DIRS_MAX 0
param set-default SDLOG_MISSION 3
param set-default SDLOG_MODE 0
param set-default SDLOG_PROFILE 1
param set-default SDLOG_UTC_OFFSET 0

# Circuit Breaker
param set-default CBRK_FLIGHTTERM 0 # Termination enabled
param set-default CBRK_IO_SAFETY 22027
param set-default CBRK_SUPPLY_CHK 894281

# Commander
param set-default COM_ARM_WO_GPS 0
param set-default COM_DISARM_LAND 2
param set-default COM_DISARM_PRFLT 15.0
param set-default COM_ARM_EKF_YAW 0.5
param set-default COM_RCL_EXCEPT 4
param set COM_ARM_MAG_STR 1 # Deny arming in strong magnetic disturbance

# Mavlink
param set-default MAV_2_MODE 1
param set-default SER_WIFI_BAUD 460800

# RTCM channels
param set-default GPS_RTCM_LORA_ID 25
param set-default GPS_RTCM_WIFI_ID 26
