#!/bin/sh
#
# @name Kaiken with u-blox gnss receiver
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Nikita Rodichenko <nsr@flyfire.io>
#

. ${R}etc/init.d/airframes/ff_base2
. ${R}etc/init.d/airframes/ff_kaiken

param set GPS_1_PROTOCOL 1 # u-blox
param set GPS_UBX_DYNMODEL 7
