#!/bin/sh
#
# @name Base frame #2 for FlyFire drones
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Vladimir Savelyev <vms@flyfire.io>
#


# Smart battery
param set-default BAT1_N_CELLS 2
param set-default BAT1_SOURCE 1
param set-default BAT_LOW_THR 0.15
param set-default BAT_CRIT_THR 0.07
param set-default BAT_EMERGEN_THR 0.05

# GNSS
param set-default GPS_1_CONFIG 201
param set-default GPS_SAT_INFO 1
param set-default GPS_RTCM_LORA_ID 25
param set-default GPS_RTCM_WIFI_ID 26

# EKF
param set-default EKF2_ABL_LIM 0.4
param set-default EKF2_GPS_POS_Z 0.0
param set-default EKF2_GPS_P_GATE 5.0
param set-default EKF2_GPS_P_NOISE 0.2
param set-default EKF2_GPS_V_GATE 5.0
param set-default EKF2_GPS_V_NOISE 0.15
param set-default EKF2_HGT_REF 1 # GPS is reference source of height data
param set-default EKF2_REQ_HDRIFT 0.05
param set-default EKF2_REQ_VDRIFT 0.05
param set-default EKF2_MAG_MIN_ALT -1.0 # takeoff without mag disabled

# RC
param set-default COM_FLTMODE1 8
param set-default COM_FLTMODE2 8
param set-default COM_FLTMODE3 1
param set-default COM_FLTMODE4 1
param set-default COM_FLTMODE5 2
param set-default COM_FLTMODE6 2
param set-default RC1_MAX 2005
param set-default RC1_MIN 982
param set-default RC1_TRIM 1495
param set-default RC2_MAX 2005
param set-default RC2_MIN 982
param set-default RC2_TRIM 1495
param set-default RC3_MAX 2005
param set-default RC3_MIN 982
param set-default RC3_TRIM 982
param set-default RC4_MAX 2005
param set-default RC4_MIN 982
param set-default RC4_TRIM 1495
param set-default RC5_MAX 2005
param set-default RC5_MIN 982
param set-default RC5_TRIM 1495
param set-default RC6_MAX 2005
param set-default RC6_MIN 982
param set-default RC6_TRIM 1495
param set-default RC7_MAX 2005
param set-default RC7_MIN 982
param set-default RC7_TRIM 1495
param set-default RC_CHAN_CNT 18
param set-default RC_MAP_FLTMODE 5
param set-default RC_MAP_PITCH 1
param set-default RC_MAP_POSCTL_SW 0
param set-default RC_MAP_RATT_SW 0
param set-default RC_MAP_RETURN_SW 0
param set-default RC_MAP_ROLL 2
param set-default RC_MAP_STAB_SW 0
param set-default RC_MAP_THROTTLE 3
param set-default RC_MAP_YAW 4

# Geofence
param set-default GF_ALTMODE 0
param set-default GF_COUNT -1
param set-default GF_SOURCE 1
if param compare SYS_PROD_CONF 1
then
	param set-default GF_ACTION 5 # Land mode on softfence breach
	param set-default GF2_ACTION 4 # Terminate on hardfence breach
else
	param set-default GF_ACTION 1 # Warning on softfence breach
	param set-default GF2_ACTION 5 # Land mode on hardfence breach
fi

# Pathcontrol
param set-default PC_ACTION 0 # Disabled
param set-default PC_ACCEPT_R 10.0

# RTL
param set-default RTL_CONE_ANG 0
param set-default RTL_DESCEND_ALT 6
param set-default RTL_LAND_DELAY 5.0
param set-default RTL_MIN_DIST 0.0
param set-default RTL_RETURN_ALT 10
param set-default RTL_TYPE 0
param set-default RTL_TIME_MARGIN -1
param set-default RTL_TIME_FACTOR 0

# Navigation Tuning & Speeds
param set-default MPC_MANTHR_MIN 0.08
param set-default MPC_MAN_TILT_MAX 35
param set-default MPC_POS_MODE 0
param set-default MPC_THR_HOVER 0.50
param set-default MPC_TILTMAX_AIR 50
param set-default MPC_TILTMAX_LND 12.0
param set-default MPC_TKO_RAMP_T 1.0
param set-default MPC_TKO_SPEED 2.0
param set-default MPC_VELD_LP 5.0
param set-default MPC_XY_CRUISE 5.0
param set-default MPC_XY_ERR_MAX 2.0
param set-default MPC_XY_MAN_EXPO 0.6
param set-default MPC_XY_P 1.2
param set-default MPC_XY_TRAJ_P 0.5
param set-default MPC_XY_VEL_ALL -10.0
param set-default MPC_XY_VEL_D_ACC 0.4
param set-default MPC_XY_VEL_I_ACC 2.0
param set-default MPC_XY_VEL_P_ACC 5.0
param set-default MPC_XY_VEL_MAX 10
param set-default MPC_Z_V_AUTO_DN 3.0
param set-default MPC_Z_V_AUTO_UP 4.0
param set-default MPC_YAWRAUTO_MAX 45
param set-default MPC_Z_VEL_MAX_UP 4.0
param set-default MPC_OB_SP_DELAY 350
param set-default MPC_Z_VEL_MAX_DN 3.0
param set-default MPC_LAND_SPEED 0.1
param set-default MPC_LAND_ALT1 10
param set-default MPC_LAND_ALT2 0.5

param set-default NAV_ACC_RAD 1.2
param set-default NAV_RCL_ACT 0
param set-default LNDMC_ROT_MAX 80
param set-default LNDMC_TRIG_TIME 1

# Logging
param set-default SDLOG_DIRS_MAX 0
param set-default SDLOG_MISSION 3
param set-default SDLOG_UTC_OFFSET 0

# Circuit Breaker
param set-default CBRK_IO_SAFETY 22027
param set-default CBRK_SUPPLY_CHK 894281
param set-default CBRK_FLIGHTTERM 0 # Termination enabled

# Commander
param set-default COM_ARM_WO_GPS 0
param set-default COM_DISARM_LAND 2
param set-default COM_DISARM_PRFLT 15.0
param set-default COM_ARM_EKF_YAW 0.5
param set-default COM_RCL_EXCEPT 4
param set-default COM_FAIL_ACT_T 0
param set-default COM_OBL_RC_ACT 4
param set-default COM_POSCTL_NAVL 1 # Land/Descend
param set-default COM_LOW_BAT_ACT 0

# Mavlink
param set-default MAV_2_MODE 1
param set-default SER_WIFI_BAUD 460800
