#!/bin/sh
#
# @name Base frame #1 for FlyFire drones
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Vladimir Savelyev <vms@flyfire.io>
#

. ${R}etc/init.d/rc.mc_defaults

# Smart battery
param set BAT1_N_CELLS 2
param set BAT1_SOURCE 1
param set BAT_LOW_THR 0.15
param set BAT_CRIT_THR 0.07
param set BAT_EMERGEN_THR 0.05

# GNSS
param set GPS_1_CONFIG 201

# EKF
param set EKF2_ABL_LIM 0.4
param set EKF2_GPS_POS_Z 0.0
param set EKF2_GPS_P_GATE 5.0
param set EKF2_GPS_P_NOISE 0.3
param set EKF2_GPS_V_GATE 5.0
param set EKF2_GPS_V_NOISE 0.3
param set EKF2_REQ_HDRIFT 0.05
param set EKF2_REQ_VDRIFT 0.05
param set EKF2_MAG_MIN_ALT -1.0 # takeoff without mag disabled

# RC
param set COM_FLTMODE1 8
param set COM_FLTMODE2 8
param set COM_FLTMODE3 1
param set COM_FLTMODE4 1
param set COM_FLTMODE5 2
param set COM_FLTMODE6 2
param set RC1_MAX 2005
param set RC1_MIN 982
param set RC1_TRIM 1495
param set RC2_MAX 2005
param set RC2_MIN 982
param set RC2_TRIM 1495
param set RC3_MAX 2005
param set RC3_MIN 982
param set RC3_TRIM 982
param set RC4_MAX 2005
param set RC4_MIN 982
param set RC4_TRIM 1495
param set RC5_MAX 2005
param set RC5_MIN 982
param set RC5_TRIM 1495
param set RC6_MAX 2005
param set RC6_MIN 982
param set RC6_TRIM 1495
param set RC7_MAX 2005
param set RC7_MIN 982
param set RC7_TRIM 1495
param set RC_CHAN_CNT 18
param set RC_MAP_FLTMODE 5
param set RC_MAP_PITCH 1
param set RC_MAP_POSCTL_SW 0
param set RC_MAP_RATT_SW 0
param set RC_MAP_RETURN_SW 0
param set RC_MAP_ROLL 2
param set RC_MAP_STAB_SW 0
param set RC_MAP_THROTTLE 3
param set RC_MAP_YAW 4

# Geofence
param set GF_ALTMODE 0
param set GF_COUNT -1
param set GF_SOURCE 1
param set GF_ACTION 1 # Warning
param set GF2_ACTION 5 # Land mode

# Pathcontrol
param set PC_ACTION 0 # Disabled
param set PC_ACCEPT_R 10.0

# RTL
param set RTL_CONE_ANG 0
param set RTL_DESCEND_ALT 6
param set RTL_LAND_DELAY 5.0
param set RTL_MIN_DIST 0.0
param set RTL_RETURN_ALT 10
param set RTL_TYPE 0
param set RTL_TIME_MARGIN -1
param set RTL_TIME_FACTOR 0

# Navigation Tuning & Speeds
param set MPC_MANTHR_MIN 0.08
param set MPC_MAN_TILT_MAX 35
param set MPC_POS_MODE 0
param set MPC_THR_HOVER 0.50
param set MPC_TILTMAX_AIR 45
param set MPC_TILTMAX_LND 12.0
param set MPC_TKO_RAMP_T 3.0
param set MPC_TKO_SPEED 1.5
param set MPC_VELD_LP 5.0
param set MPC_XY_CRUISE 5
param set MPC_XY_ERR_MAX 2.0
param set MPC_XY_MAN_EXPO +
param set MPC_XY_P 0.95
param set MPC_XY_TRAJ_P 0.5
param set MPC_XY_VEL_ALL -10.0
param set MPC_XY_VEL_D_ACC 0.2
param set MPC_XY_VEL_I_ACC  0.4
param set MPC_XY_VEL_P_ACC 1.8
param set MPC_Z_V_AUTO_DN 1.5
param set MPC_Z_V_AUTO_UP 3.0
param set MPC_XY_VEL_MAX 10
param set MPC_YAWRAUTO_MAX 45
param set MPC_Z_VEL_MAX_UP 3
param set MPC_OB_SP_DELAY 350
param set MPC_Z_VEL_MAX_DN 3
param set MPC_LAND_SPEED 0.3
param set MPC_LAND_ALT1 10
param set MPC_LAND_ALT2 1

param set NAV_ACC_RAD 1.2
param set NAV_RCL_ACT 0
param set LNDMC_ROT_MAX 80
param set LNDMC_TRIG_TIME 1

# Logging
param set SDLOG_DIRS_MAX 0
param set SDLOG_MISSION 3
param set SDLOG_MODE 1
param set SDLOG_PROFILE 2048
param set SDLOG_UTC_OFFSET 0

# Circuit Breaker
param set CBRK_IO_SAFETY 22027
param set CBRK_SUPPLY_CHK 894281
param set CBRK_FLIGHTTERM 121212 # Termination disabled

# Commander
param set COM_ARM_WO_GPS 0
param set COM_DISARM_LAND 2
param set COM_DISARM_PRFLT 15.0
param set COM_ARM_EKF_YAW 0.5
param set COM_RCL_EXCEPT 4
param set COM_FAIL_ACT_T 0
param set COM_OBL_RC_ACT 4
param set COM_POSCTL_NAVL 1 # Land/Descend
param set COM_LOW_BAT_ACT 0

# Mavlink
param set MAV_2_MODE 1
param set SER_WIFI_BAUD 460800

# RTCM channels
param set GPS_RTCM_LORA_ID 25
param set GPS_RTCM_WIFI_ID 26
