#!/bin/sh
#
# @name Shuriken unique parameters
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Nikita Rodichenko <nsr@flyfire.io>
#

# Motors
param set PWM_MAIN_TIM0 -5
param set PWM_MAIN_FUNC1 101
param set PWM_MAIN_FUNC2 102
param set PWM_MAIN_FUNC3 103
param set PWM_MAIN_FUNC4 104
param set DSHOT_MIN 0.075
param set THR_MDL_FAC 0.3

# Rotors
param set CA_ROTOR_COUNT 4
param set CA_ROTOR0_PX 0.15
param set CA_ROTOR0_PY 0.15
param set CA_ROTOR1_PX -0.15
param set CA_ROTOR1_PY -0.15
param set CA_ROTOR2_PX 0.15
param set CA_ROTOR2_PY -0.15
param set CA_ROTOR2_KM -0.05
param set CA_ROTOR3_PX -0.15
param set CA_ROTOR3_PY 0.15
param set CA_ROTOR3_KM -0.05

# IMU
param set IMU_DGYRO_CUTOFF 30
param set IMU_GYRO_CUTOFF 70

# Sensors & Calibration
param set CAL_MAG_COMP_TYP 1
param set CAL_MAG_SIDES 63
param set CAL_MAG0_ID 527625
param set CAL_MAG0_PRIO 100
param set CAL_MAG0_ROT 40
param set CAL_MAG0_XCOMP -0.226
param set CAL_MAG0_YCOMP 0.253
param set CAL_MAG0_ZCOMP -0.031
param set CAL_MAG1_ID 0
param set CAL_MAG1_ROT 40
param set CAL_MAG1_PRIO 0
param set SENS_MAG_AUTOROT 0
param set SENS_MAG_SIDES 63
param set SENS_BOARD_ROT 6
param set SENS_BOARD_X_OFF 0.001
param set SENS_BOARD_Y_OFF 0.001
param set EKF2_HGT_REF 0 # baro fusion disabled
param set GPS_1_PROTOCOL 6 # NMEA
param set SER_GPS1_BAUD 460800

# PID Tuning
param set MC_PITCHRATE_D 0.001
param set MC_PITCHRATE_I 0.2
param set MC_PITCHRATE_K 1
param set MC_PITCHRATE_MAX 220
param set MC_PITCHRATE_P 0.1
param set MC_PITCH_P 6.5
param set MC_ROLLRATE_D 0.001
param set MC_ROLLRATE_K 1
param set MC_ROLLRATE_MAX 220
param set MC_ROLLRATE_P 0.1
param set MC_ROLL_P 6.5
param set MC_YAWRATE_MAX 60
param set MC_YAWRATE_P 0.2
param set MC_YAW_P 2.5
