#!/bin/sh
#
# @name Shuriken unique parameters
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Nikita Rodichenko <nsr@flyfire.io>
#

# Motors
param set-default PWM_MAIN_TIM0 -5
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default DSHOT_MIN 0.075
param set-default THR_MDL_FAC 0.3

# Rotors
param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.0553
param set-default CA_ROTOR0_PY 0.0566
param set-default CA_ROTOR0_PZ 0.0177
param set-default CA_ROTOR0_KM 0.016

param set-default CA_ROTOR1_PX -0.0567
param set-default CA_ROTOR1_PY -0.0566
param set-default CA_ROTOR1_PZ 0.0177
param set-default CA_ROTOR1_KM 0.016

param set-default CA_ROTOR2_PX 0.0553
param set-default CA_ROTOR2_PY -0.0566
param set-default CA_ROTOR2_PZ 0.0177
param set-default CA_ROTOR2_KM -0.016

param set-default CA_ROTOR3_PX -0.0567
param set-default CA_ROTOR3_PY 0.0566
param set-default CA_ROTOR3_PZ 0.0177
param set-default CA_ROTOR3_KM -0.016

# IMU
param set-default IMU_DGYRO_CUTOFF 30
param set-default IMU_GYRO_CUTOFF 70

# EKF
param set-default EKF2_BARO_CTRL 1 # baro fusion enabled
param set-default EKF2_GND_EFF_DZ 0.5

param set-default EKF2_IMU_POS_X 0.0066
param set-default EKF2_IMU_POS_Y -0.0119
param set-default EKF2_IMU_POS_Z 0.02

param set-default EKF2_IMU_POS_X 0.0
param set-default EKF2_IMU_POS_Y 0.0
param set-default EKF2_IMU_POS_Z -0.0273

# Sensors & Calibration
param set-default SENS_MAG_AUTOROT 0
param set-default CAL_MAG_SIDES 63
param set-default CAL_MAG0_ID 527625
param set-default CAL_MAG0_PRIO 100
param set-default CAL_MAG0_ROT 40
param set-default CAL_MAG1_ID 0
param set-default CAL_MAG1_ROT 40
param set-default CAL_MAG1_PRIO 0

param set-default CAL_MAG_COMP_TYP 1
param set-default CAL_MAG0_XCOMP -0.226
param set-default CAL_MAG0_YCOMP 0.253
param set-default CAL_MAG0_ZCOMP -0.031

param set-default SENS_BOARD_ROT 6
param set-default SENS_BOARD_X_OFF 0.001
param set-default SENS_BOARD_Y_OFF 0.001

# PID Tuning
param set-default MC_PITCHRATE_P 0.1
param set-default MC_PITCHRATE_I 0.2
param set-default MC_PR_INT_LIM 0.3
param set-default MC_PITCHRATE_D 0.001
param set-default MC_PITCHRATE_K 1
param set-default MC_PITCHRATE_FF: 0.0
param set-default MC_PITCHRATE_MAX 220
param set-default MC_PITCH_P 6.5

param set-default MC_ROLLRATE_P 0.1
param set-default MC_ROLLRATE_I 0.2
param set-default MC_RR_INT_LIM 0.3
param set-default MC_ROLLRATE_D 0.001
param set-default MC_ROLLRATE_K 1
param set-default MC_ROLLRATE_FF 0.0
param set-default MC_ROLLRATE_MAX 220
param set-default MC_ROLL_P 6.5

param set-default MC_YAWRATE_MAX 60
param set-default MC_YAWRATE_P 0.2
param set-default MC_YAW_P 2.5

# LOG
param set-default SDLOG_MODE 0
param set-default SDLOG_PROFILE 33
